[workspace]
members = [
	"src/float",
	"src/load",
	"src/analyze",
	"src/describe",
    "src/data_visualization",
	"src/model",
	"src/hypothesis",
	"src/train",
	"src/predict",
]
resolver = "2"


[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
