[workspace]
members = [
	"src/float",
	"src/load",
	"src/describe",
	"src/model",
	"src/hypothesis",
	"src/train",
]
resolver = "2"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
