[package]
name = "float"
version = "0.1.0"
edition = "2021"
authors = [
	"jucapik <jucapik@student.42.fr>",
	"adelille <adelille@student.42.fr>",
]
description = "basic `type Float = f32` or `f64`"

[dependencies]
